verbose: false
reporting:
    reports:
        - lcov
        - json
        - text
check:
    global:
        statements: 100
        branches: 100
    each:
        statements: 100
        branches: 100
